name: Test oppfest

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  oppfest:
    runs-on: ubuntu-latest
    name: oppfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Test oppfest
        uses: ./oppfest