name: 'Open Peer Power: oppfest'
description: 'Open Peer Power: oppfest'
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"

    - shell: bash
      run: |
        docker build ${{ github.action_path }} -f ${{ github.action_path }}/Dockerfile -t oppfest

    - shell: bash
      run: |
        docker run --rm -v ${{ github.workspace }}://github/workspace oppfest
