name: 'Open Peer Power helper: verify-version'
description: 'GitHub action helper: verify-version'
inputs:
  ignore-dev:
    description: Skip check if the branch is 'dev'
    required: false
    default: false
  ignore-main:
    description: Skip check if the branch is 'main'
    required: false
    default: false
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        python3 -m pip install setuptools

        setup_version="$(python3 setup.py -V)"
        branch_version=$(echo "${{ github.ref }}" | awk -F"/" '{print $NF}' )

        if [[ "${{ inputs.ignore-dev }}" =~ true|True ]] && [ "${branch_version}" == "dev" ]; then
          exit 0
        elif [[ "${{ inputs.ignore-main }}" =~ true|True ]] && [ "${branch_version}" == "main" ]; then
          exit 0
        elif [ "${setup_version}" != "${branch_version}" ]; then
          echo "Version of tag ${branch_version} don't match with ${setup_version}!"
          exit 1
        fi
