name: Test oppfest

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: oppfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Test oppfest
        uses: ./oppfest
